### ISSUE TITLE
Get together as a team

### ISSUE THREAD

**Issue by jbwoo9779** [StanfordCS194/The-Giving-World#1]
Hi folks,

Please arrange to meet one another, find a good SGM time that works for you and get after the [Startup Your Team](https://github.com/StanfordCS194/Home/blob/master/Startup-Your-Team.md) assignment

Jeff

**Comment by ajacobs7** [comment]
Hey guys! Excited to work with you! Here's a when2meet for brainstorming:
https://www.when2meet.com/?7728307-TAaJa

**Comment by ajacobs7** [comment]
What do you guys think about making a slack for communication?

**Comment by kkenealy** [comment]
That sounds great to me!

**Comment by joshduf** [comment]
Sounds great, thanks for organizing this!

**Comment by ajacobs7** [comment]
Okay, I made a slack. Let me know if you didn't get an invitation to join it.

**Comment by anzioka** [comment]
Hi @ajacobs7 can you resend me the slack invite? Thanks

**Comment by ajacobs7** [comment]
@anzioka @joshduf @kkenealy So the slack says that you are all members already. Maybe it added you automatically since the slack is part of the "Stanford Organization" and that's why some of you haven't gotten an invite.

Try going to this link and logging in with Stanford credentials: 
https://cs194-team-11.slack.com

If that doesn't work, maybe go to https://stanford.enterprise.slack.com and search for CS194-Team-11.

**Comment by joshduf** [comment]
It worked for me.
